### PR TITLE
blog layout

### PR DESCRIPTION
**Pull request by vsutan**
Yo, I still couldn't figure out how to access jekyll variables from the include.html. But I guess for this one, we can just fix the path. Meanwhile, I'll figure out how to access the var so we dont' have to keep changing it.

Let me know if there is any issue,

-V-

### CODE REVIEW

**Comment by vsutan** [comment]
yo, I actually fixed the path. you can safely pull it now.

**Comment by mbigles1** [comment]
Sweet, i'll pull today.

**Comment by mbigles1** [comment]
@vsutan there is an atom file. is that for some feed. do you have to keep recreating or is it automatic?

**Comment by mbigles1** [comment]
check it out. pushed to clqye.com
https://www.clyqe.com/blog/Travel-With-Your-Gear

**Comment by vsutan** [comment]
hm..., the picture got messed up. it was bigger.

**Comment by mbigles1** [comment]
I dont know if its a config issue or the image itself. there was a merge conflicts with the actual image and wasn't sure if it was due to a different size image.

**Pull request merged**
